# -*- coding: utf-8 -*-
"""
/***************************************************************************
 XinoCartographic
                                 A QGIS plugin
 Este complemente nos ayuda a crear planos de impresion leyendo los datos desde un libro de excel
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-02
        copyright            : (C) 2025 by Emmanuel Rodriguez Garcia
        email                : isc.emmanuel.itd@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load XinoCartographic class from file XinoCartographic.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .xino_cartographic import XinoCartographic
    return XinoCartographic(iface)
